apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-jkbot
  namespace: default
  labels:
    app: discord-jkbot

spec:
  replicas: 1

  selector:
    matchLabels:
      app: discord-jkbot

  template:
    metadata:
      labels:
        app: discord-jkbot

    spec:
      containers:
        - name: bot

          image: asia-northeast1-docker.pkg.dev/denkitv-502714/docker/discord-jkbot:latest

          imagePullPolicy: Always

          env:
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: discord-jkbot-secret
                  key: DISCORD_TOKEN

            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: discord-jkbot-secret
                  key: OPENAI_API_KEY

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"